site_name: Juan Bautista Talens Felis
site_author: Juan Bautista Talens Felis
site_url: https://juatafe.github.io

theme:
  name: material
  logo: img/logojaume.png
  favicon: img/logojaume.png
  language: ca
  features:
    - navigation.footer
    - navigation.top
    - toc.follow
  palette: 
    - scheme: default
      primary: 'red'  # 
      accent: 'grey'   # Gris claro UPV
      toggle:
        icon: material/brightness-7 
        name: Mode clar
    - scheme: slate
      primary: 'red'  # 
      accent: 'grey'   # Gris claro UPV
      toggle:
        icon: material/brightness-1
        name: Mode oscur
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:jb.talensfelis@edu.gva.es
      name: Contacte

copyright: Copyright &copy; 2024 - JB Talens - <a href="#__consent">Change cookie settings</a>

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search